<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3Z3WM9p\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3Z3WM9p/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container3Z3WM9p.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container3Z3WM9p\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container3Z3WM9p\App_KernelDevDebugContainer([
    'container.build_hash' => '3Z3WM9p',
    'container.build_id' => '21241f01',
    'container.build_time' => 1716714052,
], __DIR__.\DIRECTORY_SEPARATOR.'Container3Z3WM9p');
